"""add suggested_fix

Revision ID: a2f48878f8d9
Revises: 001_initial
Create Date: 2026-08-22 17:12:49.604490
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'a2f48878f8d9'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('suggested_fix', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'suggested_fix')
    # ### end Alembic commands ###
